CREATE TABLE IF NOT EXISTS springbatch.BRANCHE_BRA(
    BRA_ID serial PRIMARY KEY,
    BRA_CODE VARCHAR(50),
    BRA_LIBELLE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS springbatch.GARANTIE_GAR(
    GAR_ID serial PRIMARY KEY,
    GAR_CODE VARCHAR(25),
    GAR_LIBELLE VARCHAR(50),
    GAR_LCI NUMERIC
);

CREATE TABLE IF NOT EXISTS springbatch.PRODUIT_PRO(
    PRO_ID serial PRIMARY KEY,
    PRO_CODE VARCHAR(50),
    PRO_LIBELLE VARCHAR(50),
    PRO_DESCRIPTION VARCHAR(500),
    PRO_TAUXFRAISGESTION NUMERIC(8,4)
);

CREATE TABLE IF NOT EXISTS springbatch.GARANTIE_PRODUIT_GPR(
    GPR_ID serial PRIMARY KEY,
    GPR_FK_PRO_ID INT NOT NULL,
    GPR_FK_GAR_ID INT NOT NULL,
    GPR_LCI NUMERIC,
    FOREIGN KEY(GPR_FK_PRO_ID) REFERENCES PRODUIT_PRO(PRO_ID),
    FOREIGN KEY(GPR_FK_GAR_ID) REFERENCES GARANTIE_GAR(GAR_ID)
);

CREATE TABLE IF NOT EXISTS springbatch.FUSION_BRANCHE_GARANTIE_FUS(
    FUS_ID serial PRIMARY KEY,
    FUS_CODE VARCHAR(500),
    FUS_LIBELLE VARCHAR(500)
);